title: IDLE Press Arcade
description: Testing out the a starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://rocket5.github.io/justhedocs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  Rocket 5 Studios: https://rocket5.ca

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# External navigation links
nav_external_links:
  - title: Just the Docs on GitHub
    url: https://github.com/just-the-docs/just-the-docs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false